// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using unshaped_gamedata_api.Data;

#nullable disable

namespace unshaped_gamedata_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("unshaped_gamedata_api.Models.GameData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Current")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Like")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("MultiPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimePlayed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameData");
                });
#pragma warning restore 612, 618
        }
    }
}
